# Generated by Django 5.0.6 on 2024-05-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccount',
            name='is_active',
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний'), ('banned', 'Заблокований')], default='active', max_length=10),
        ),
    ]
