# Generated by Django 5.0.6 on 2024-05-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_parserrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserrun',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
