# Generated by Django 5.0.6 on 2024-06-02 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_alter_parserrun_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccountStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_videos_amount', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='parser.instagramaccount')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='parser.parserrun')),
            ],
        ),
    ]
